### ISSUE TITLE
Possible publication on hex.pm

### ISSUE THREAD

**Issue by drobakowski** [bipthelin/mochiweb_util#1]
Hi @bipthelin, is there any chance to publish this or the fork from [kivra/mochiweb_util](https://github.com/kivra/mochiweb_util) as a package on [hex.pm](https://hex.pm)? `mochiweb` it self uses a MIT license, so I think there should be no problem from this point of view. I could prepare a PR with the missing `app.src` attributes for you if you like? This would be a nice addition for the PR https://github.com/kivra/restclient/pull/16.

**Comment by bipthelin** [comment]
Please provide a PR for https://github.com/kivra/mochiweb_util
